- prefpicker/templates/browser-fuzzing.yml
I've chosen `null` over `false` to clarify that the intention is not to change from the shipping state, and this will mean the pref value continues to follow shipping state, should that ever change.
> Don't set media.track.enabled, media.getusermedia.audiocapture.enabled or dom.paintWorklet.enabled

- prefpicker/templates/browser-fuzzing.yml
By default `apz.nonwr.activate_all_scroll_frames` will be set randomly to either `true` or `false`.
When using `webrender` variant `apz.wr.activate_all_scroll_frames` will be  set randomly to either `true` or `false`.
> Add apz.(non)wr.activate_all_scroll_frames

- prefpicker/templates/browser-fuzzing.yml
It hasn't been doing anything for years. I'm removing references to it in https://bugzilla.mozilla.org/show_bug.cgi?id=1706104, but it's never read, but is set.
> Remove `media.useAudioChnanelAPI`

- prefpicker/templates/browser-fuzzing.yml
Revert this once https://bugzilla.mozilla.org/show_bug.cgi?id=1716622 has been fixed.
> Disable largeArrayBuffers

- prefpicker/templates/browser-fuzzing.yml
Requested by @saschanaz.  This API will be enabled by default in nightly soon.  This will allow us to get a jump on fuzzing.
> Enable WebLocks API by default

- prefpicker/templates/browser-fuzzing.yml
- `layout.css.conic-gradient.enabled` is removed in https://bugzil.la/1679714
- `layout.css.contain.enabled` is removed in https://bugzil.la/1626458
> Remove obsolete layout prefs

- prefpicker/templates/browser-fuzzing.yml
Is there any way to indicate a dependency? 
It's not clear to me that fuzz tests where you `pipeTo && !writableStreams` make any sense...
> Add Writable Streams fuzzing 

- .pre-commit-config.yaml
- prefpicker/templates/browser-fuzzing.yml
- prefpicker/templates/schema.json
Adds a JSON schema and pre-commit hook for validating the template files.  Do not land until https://github.com/MozillaSecurity/prefpicker/commits/updates is merged.
> Add pre-commit hook for verifying template schema

- prefpicker/templates/browser-fuzzing.yml
`gfx.e10s.font-list.shared=true` is now the default.
See [Bug 1694174](https://bugzilla.mozilla.org/show_bug.cgi?id=1694174).
> Remove gfx.e10s.font-list.shared entry

- prefpicker/templates/browser-fuzzing.yml
This is used to force enable a11y.
> Add a11y variant

- src/prefpicker/templates/browser-fuzzing.yml
setHTML functionality is behind a new pref: https://bugzilla.mozilla.org/show_bug.cgi?id=1805632
> feat: enable dom.security.setHTML.enabled

- tox.ini
Another failure due to tox 4 update
> ci: fix semantic-release

- src/prefpicker/templates/browser-fuzzing.yml
Closes https://github.com/MozillaSecurity/prefpicker/issues/76
> fix: remove unnecessary pref layout.css.named-pages.enabled

- src/prefpicker/templates/browser-fuzzing.yml
The behavior enabled by these prefs is now default and the prefs no longer exist.
> fix: remove unnecessary writable-streams variant

- src/prefpicker/templates/browser-fuzzing.yml
Allows additional input elements to accept datetime values.
> feat: add dom.forms.datetime.others

- src/prefpicker/templates/browser-fuzzing.yml
Maximum size in kilobytes that we allow to allocate an imgFrame. This helps avoid OOMs when loading fuzzed images. Setting limit 62500=(4000x4000x4)/1024.
> feat: add image.mem.max_legal_imgframe_size_kb=62500

- src/prefpicker/templates/browser-fuzzing.yml
- image.animated.decode-on-demand.threshold-kb sometimes use default
- image.cache.size sometimes use default
- image.avif.sequence.enabled is now enabled by default
- image.multithreaded_decoding.limit no longer exists
> fix: update image related prefs

- src/prefpicker/templates/browser-fuzzing.yml
Fetchkeepalive should be functional for non-worker fetch requests.
> Bug  1900661 - Add dom.fetchKeepalive.enabled to fuzzing prefs

- src/prefpicker/templates/browser-fuzzing.yml
> fix: webgl.colorspaces.prototype is now on by default

- src/prefpicker/templates/browser-fuzzing.yml
The feature this pref enables will never be enabled in Firefox.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1936080.
> feat: remove layout.css.overflow-clip-box.enabled

- src/prefpicker/templates/browser-fuzzing.yml
Navigation API is still a work in progress, therefore there are lots of fuzzing bugs found which point to the unfinished implementation.
Let's disable fuzzing for Navigation API until the implementation is more mature.
> feat: disable dom.navigation.webidl.enabled

- src/prefpicker/templates/browser-fuzzing.yml
It appears that some checks are hidden behind `webgl.force-enabled`.
> feat: re-enable webgl.force-enabled
